config/routes.rb
Rails.application.routes.draw do
  get 'experiments/new'
  get 'sessions/new'
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'  
  resources :users, :only => [:index, :update]
#  get '/division', to: 'static_pages#division'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  resources :account_activations, only: [:edit]
  resources :divisions, only: [:index, :create, :show, :edit, :update, :destroy]
  post '/division/marge', to: 'divisions#marge'
  resources :records, only: [:index, :create, :edit, :update, :destroy]
  root 'static_pages#home'
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  include SessionsHelper

  def home
    if logged_in?
      @record = Record.new
      @records = Record.where(user_id: session[:user_id]).where(disabled: nil).order("created_at DESC").limit(10)
      @divisions = Division.where(user_id: session[:user_id]).where(disabled: nil).order("name")
    end
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/_record_form.html.erb
<%= form_with scope: :record, url: records_path do |f| %>
  <ul>
  <%= f.label "会計科目タイプ" %>
  <%= f.text_field :account, class: 'form-control' %>
  </ul>
  <ul>
  <%= f.label "金額" %>
  <%= f.number_field :amount, class: 'form-control' %>
  </ul>
  <ul>
  <%= f.label "消費税率" %>
  <p>
  <span class="hidden"><%= f.radio_button :tax, '10' %> 10%</span>
  <%= f.radio_button :tax, '8', {:checked => true} %> 8%
  <%= f.radio_button :tax, '0' %> 対象外
  </p>
  </ul>
  <ul>
  <%= f.label "発生日" %><br>
  <%= f.date_select :when, class: 'form-control' %>
  </ul>
  <ul>
  <%= f.label "支払先" %><small> or交通費は行き先</small>
  <%= f.text_field :where, class: 'form-control' %>
  </ul>
  <ul>
  <%= f.label "売上先" %><small> or交通費は出発地</small>
  <%= f.text_field :where_from, class: 'form-control' %>
  </ul>
  <ul>
  <%= f.label "数量" %>
  <%= f.number_field :quantity, class: 'form-control' %>
  </ul>
  <ul>
  <%= f.label "発生した事業領域" %>
  <%= f.text_field :division, class: 'form-control' %>
  </ul>
  <%= f.hidden_field :user_id, :value => session[:user_id] %>

  <ul>
  <%= f.submit "記帳する", class: "btn btn-primary" %>
  </ul>
<% end %>

app/views/static_pages/_sign_in_form.html.erb
<%= form_with url: login_path do |f| %>

  <%= f.label :email %>
  <%= f.email_field :email, class: 'form-control' %>

  <%= f.label :password %>
  <%= f.password_field :password, class: 'form-control' %>

  <%= f.label :remember_me, class: "checkbox inline" do %>
    <%= f.check_box :remember_me %>
    <span>ログイン状態を端末に記憶する</span>
  <% end %>

  <%= f.submit "ログイン", class: "btn btn-primary" %>
<% end %>

app/views/static_pages/division.html.erb
<% provide( :title, "事業一覧" ) %>
<h1>あなたの事業一覧</h1>

app/views/static_pages/home.html.erb
<% provide( :title, "Home" ) %>
<% if !logged_in? %>
  <div class="center jumbotron">
    <h1>Account Book</h1>
    <h2>個人事業主のための簡易帳簿システム</h2>

    <div class="row group">
      <div class="col-sm-8 col-sm-offset-2">
      <%= render 'sign_in_form' %>
      </div>
    </div>
    <div class="row group">
      <p col-sm-8 col-sm-offset-2>初めて利用される方はこちらから<br>
      <%= link_to "アカウント作成", signup_path, class:"btn" %>
      </p>
    </div>
  </div>
<% else %>
  <main class="col-sm-10 col-sm-offset-1">
    <h1 class="h4 y-spacing">
    <%= "こんにちは、 #{session[:user_name]}さん"%>
    </h1>
    <div class="col-sm-4", id="record_form">
      <%= form_with scope: :record, url: records_path do |f| %>
        <%= render 'records/form', f: f, account_name: "", division_name: "" %>
        <%= f.hidden_field :user_id, :value => session[:user_id] %>
        <ul>
        <%= f.submit "記帳する", class: "btn btn-primary", id: "record_submit" %>
        </ul>
      <% end %>
    </div>
    <div class="col-sm-8">
    <% if @records.present? %>
      <p>
        最近記帳した30件
      </p>
      <%= render @records %>
    <% elsif @divisions.present? %>
      <p>
        まだ記帳された記録がありません。フォームから記帳を始めましょう！
      </p>
    <% else %>
      <p>
        記帳を始める前に、まずは事業タブからあなたの事業を登録しましょう！<br>
        事業をアプリケーションに登録することで記帳が可能になります。
      </p>
    <% end %>
    </div>
  </main>
<% end %>