config/routes.rb
Rails.application.routes.draw do
  get 'experiments/new'
  get 'sessions/new'
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'  
  resources :users, :only => [:index, :update]
#  get '/division', to: 'static_pages#division'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  resources :account_activations, only: [:edit]
  resources :divisions, only: [:index, :create, :show, :edit, :update, :destroy]
  post '/division/marge', to: 'divisions#marge'
  resources :records, only: [:index, :create, :edit, :update, :destroy]
  root 'static_pages#home'
end

app/models/division.rb
class Division < ApplicationRecord
  belongs_to :user, optional: true
  has_many :records
  has_many :back_records
  validates :user_id, presence: true
  validates :name, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  attr_accessor :remember_token, :activation_token, :reset_token
  has_many :divisions
  before_save :downcase_email
  before_create :create_activation_digest 
  validates :name, presence: true, length: {maximum: 20}
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  # this does not follow internationalized domain name.
  # So you should fix if your customers use such email address.
  validates :email, presence: true, length: {maximum: 80},
              format: {with: VALID_EMAIL_REGEX},
              uniqueness: { case_sensitive: false }

  has_secure_password
  validates :password, presence: true, length: {minimum: 8}

  def self.digest(string) # you need 'self' if you call it from fixture.
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST : BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  def self.new_token # generate randam token by urlsafe_base64
    SecureRandom.urlsafe_base64
  end

  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  def authenticated?(attribute, token) # remember_token should be called from cookies.
    digest = self.send("#{attribute}_digest")
    return false if digest.nil?
    BCrypt::Password.new(digest).is_password?(token)
  end

  def forget(id)
    user = User.find_by(id: id)
    user.update_attribute(:remember_digest, nil)
  end

  def activate
    self.update_attribute(:activated, true)
    self.update_attribute(:activated_at, Time.zone.now)
  end

  def send_activation_email
    UserMailer.account_activation(self).deliver_now
  end

  def create_reset_digest
    self.reset_token = User.new_token
    update_attribute(:reset_digest, User.digest(reset_token))
    update_attribute(:reset_sent_at, Time.zone.now)
  end

  def send_password_reset_email
    @time = Time.zone.now
    UserMailer.password_reset(self, @time).deliver_now
  end

  def password_reset_expired?
    reset_sent_at < 2.hours.ago
  end

 private

  def downcase_email
    self.email = email.downcase
  end

  def create_activation_digest
    self.activation_token = User.new_token
    self.activation_digest = User.digest(activation_token)
  end

end

app/controllers/divisions_controller.rb
class DivisionsController < ApplicationController
  before_action :get_division, only: [:edit, :update]
  before_action :validate_owner, only: [:edit, :update]
  def index
    if session[:user_id]
      @divisions = Division.where(user_id: session[:user_id]).where(disabled: nil).order("name")
      @user_id = session[:user_id]
    else
      flash[:danger] = "ログイン時のみ有効なulrです"
      redirect_to root_url
    end
  end

  def create
    division = Division.new(division_params_independent)
    if division.save
      flash[:success] = "新しい事業を登録しました"
      redirect_to divisions_path
    else
      flash[:danger] = "登録に失敗しました"
      redirect_to divisions_path
    end
  end

  def show
    if params[:id].include?("division")
      division_ids = Rack::Utils.parse_nested_query(params[:id]).map{|k,v|v}.flatten!
      division_ids.delete("")
    else
      division_ids = [params[:id]]
    end
    if division_ids.size == 0
      flash[:danger] = "集計を行う事業が選択されていません"
      redirect_to divisions_path 
    end
    @divisions=[]
    division_ids.each do |id|
      division = Division.find_by(id: id)
      @divisions << division if division
    end
    @division = Division.new
    @division.name = @divisions.size==1 ? @divisions[0].name : "マルチ集計：#{@divisions.map{|d| d.name}.join(", ")}"
    @date_a = params[:date_a] ? params[:date_a] : Time.current.beginning_of_month
    @date_z = params[:date_z] ? params[:date_z] : nil 
    @back_records = BackRecord.period(division_ids, @date_a, @date_z)
    @stats = BackRecord.stats(@back_records)
  end

  def marge
    redirect_to(controller: 'divisions', action: 'show',
      id: params[:post][:division_ids].to_query('division'))
  end

  def edit
  end

  def update
    if @division.update_attributes(division_params_independent)
      flash[:success] = "変更を反映しました"
      redirect_to divisions_path
    else
      flash[:danger] = "変更に失敗しました"
      redirect_to edit_divisions_path
    end
  end

  def destroy
    division = Division.find_by(id: params[:id])
    if division.update_attributes(disabled: Time.zone.now)
      flash[:success] = "事業を削除しました"
      redirect_to divisions_path      
    else 
      flash[:danger] = "事業の削除中にエラーが発生しました"
      redirect_to divisions_path
    end
  end

 private

  def division_params_relational
    params.require(:division).permit(:name)
  end

  def division_params_independent
    params.require(:division).permit(:user_id, :name)
  end

  def get_division
    @division = Division.find_by(id: params[:id])
  end

  def validate_owner
    unless logged_in_as_owner?(@division)
      redirect_to root_url 
    end
  end

end

app/helpers/divisions_helper.rb
module DivisionsHelper
end

app/views/divisions/_division.html.erb
<li id="division-<%= division.id %>" class="y-spacing" style="overflow:auto">
  <strong class="name">
    <%= division.name %>
  </strong>
  <span class="timestamp" style="">
    Added on <%= division.created_at.strftime("%y/%m/%d") %> .
  </span>
  <span class="pull-right">
  <%= link_to "編集", edit_division_path(division), class: "btn btn-small btn-default" %>
  <%= link_to "集計を見る", division_path(division), class: "btn btn-small btn-default"  %>
  </span>
</li>

app/views/divisions/_division_form.html.erb
<%= form_with scope: :division, url: divisions_path do |f| %>
  <ul>
  <%= f.hidden_field :user_id, :value => session[:user_id] %>
  <%= f.label :name %>
  <%= f.text_field :name, class: 'form-control' %>
  </ul>
  <ul>
  <%= f.submit "追加", class: "btn btn-primary" %>
  </ul>
<% end %>

app/views/divisions/_stat.html.erb
<% unless stat[1][:value] == 0 %>
<li> <%= "#{stat[1][:title]}: #{stat[1][:value].to_s(:delimited)}" %> </li>
<% end %>

app/views/divisions/edit.html.erb
<% provide( :title, "#{@division.name}の編集" ) %>
<main class="col-sm-10 col-sm-offset-1">
<h1><%= @division.name %>の編集</h1>
<div class="col-sm-12">
  <%= form_with model: @division, method: :patch do |f| %>
    <%= f.label "事業領域名" %>
    <%= f.text_field :name %>
    <%= f.submit "名称変更", class: "btn btn-primary pull-right" %>
  <% end %>
  <br>
</div>
<div class="col-sm-12 danger-zone ">
  <strong>Danger Zone!</strong>
  <br>
  <%= link_to "削除する", division_path(@division), method: :delete, data: {confirm: "削除しますか?", commit: "削除する", cancel: "削除しない" }, class: 'btn btn-danger pull-right' %>
  <p>
    削除してしまうと、事業に紐づいているレコードは参照できなくなります。
  </p>
</div>
</main>

app/views/divisions/index.html.erb
<% provide( :title, "事業一覧" ) %>
<main class="col-sm-10 col-sm-offset-1">
  <h1 class="h2">あなたの事業一覧</h1>
  <div class="col-sm-4">
    <%= render 'division_form' %>
  </div>
  <div class="col-sm-8">
    <% if @divisions.present? %>
    <%= render @divisions %>
    <div class="panel panel-default group">
      <div class="panel-heading">
        マルチ集計
      </div>
      <div class="panel-body">
      <%= form_with scope: :post, url: division_marge_path do |f| %>
        <%= f.collection_check_boxes :division_ids, @divisions, :id, :name do |b| %>
          <%= b.label {b.check_box + b.text } %>
        <% end %>
        <%= f.submit "集計を見る", class: "btn btn-default pull-right" %>
      <% end %>
      </div>
    </div>
    <% else %>
      <p>
        事業が登録されていない状態です、事業名を決めて追加ボタンから事業を作りましょう！
      </p>
    <% end %>
  </div>
</main>

app/views/divisions/new.html.erb
<h1>Divisions#new</h1>
<p>Find me in app/views/divisions/new.html.erb</p>

app/views/divisions/show.html.erb
<% provide( :title, "#{@division.name}の集計" ) %>
<main class="col-sm-10 col-sm-offset-1">
  <h1 class="h2"><%= @division.name %>の集計</h1>
  <p>
  集計範囲：<%= @date_a.strftime("%m月").sub("0","") %>
  <% if @date_z && !@month_z.empty? %>
    〜<%= @date_z.strftime("%m月").sub("0","") %>
  <% end %>
  </p>
  <div class="row">
    <div class="col-xs-6">
    <strong>支出</strong>
    <%= render partial: 'stat', collection: @stats[:debits], as: :stat %>
    </div>
    <div class="col-xs-6">
    <strong>収入</strong>
    <%= render partial: 'stat', collection: @stats[:credits], as: :stat %>
    </div>
  </div>
  <hr>
  <div class="row">
    <div class="col-xs-12">
      <strong>
      <%= render partial: 'stat', collection: @stats[:results], as: :stat %>
      </strong>
    </div>
  </div>
  <hr>
  <div class="row">
    <div class="col-xs-12">
    利益 / キャッシュ　差分発生要因
    <%= render partial: 'stat', collection: @stats[:factors], as: :stat %>
    </div>
  </div>
  <div class="row">
  <div class="col-xs-12">
  <span class="hidden">消費税区分別集計</span>
  <%= render partial: 'stat', collection: @stats[:info], as: :stat %>
  </div>
</div>
  <div class="row panel panel-default" style="margin-top:24px">
    <div class="panel-heading">
      <p>バックレコード(総勘定元帳)</p>
    </div>
    <div class="panel-body">
    <table class="table">
      <tr>
      <th>借方</th>
      <th>貸方</th>
      <th>金額</th>
      <th>日付</th>
      </tr>
    <%= render @back_records %>
    </table>
    </div>
  </div>
</main>