config/routes.rb
Rails.application.routes.draw do
  get 'experiments/new'
  get 'sessions/new'
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'  
  resources :users, :only => [:index, :update]
#  get '/division', to: 'static_pages#division'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  resources :account_activations, only: [:edit]
  resources :divisions, only: [:index, :create, :show, :edit, :update, :destroy]
  post '/division/marge', to: 'divisions#marge'
  resources :records, only: [:index, :create, :edit, :update, :destroy]
  root 'static_pages#home'
end

app/views/layouts/_footer.html.erb
<footer class="footer text-center">
  <span class="hidden-xs"><%= copy_right %></span>
  <% if logged_in? %> 
  <li class="visible-xs col-xs-3 h4"><%= link_to "Home", root_path %></li>
  <li class="visible-xs col-xs-3 h4"><%= link_to "事業", divisions_path %></li>
  <li class="visible-xs col-xs-3 h4"><%= link_to "帳簿", records_path %></li>
  <li class="visible-xs col-xs-3 h4"><%= link_to "Logout", logout_path, method: :delete %></li>
  <% end %>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
<div class="container">
  <span class="h3 col-sm-4 col-xs-10">
  <%= link_to "Account Book", root_path, id:"logo"%>
  </span>
  <nav class="col-sm-8 col-xs-2">
    <ul class="nav navbar-nav navbar-right">
      <% if logged_in? %>
        <li><%= link_to "Home", root_path, class: "hidden-xs" %></li>
        <li><%= link_to "事業一覧", divisions_path, class: "hidden-xs" %></li>
        <li><%= link_to "帳簿一覧", records_path, class: "hidden-xs" %></li>
        <li><%= link_to "ログアウト", logout_path, method: :delete, class: "hidden-xs" %></li>
        <% else %>
        <li><%= link_to "Home", root_path %></li>
      <% end %>
    </ul>
  </nav>
</div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
</script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= render 'layouts/shim' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
    </div>
    <% if ENV['ACCOUNT_BOOK_VERSION']=="alpha" %>
    <div class="container">
      <p>
        このアプリケーションは現在α版で公開しています。バグの報告、機能の改善提案を下記のメールにお願いします。
        ming.hentech@gmail.com<br>
        また、β版に向けて入力補助機能を実装中ですが、β版までは<a href="https://www.facebook.com/permalink.php?story_fbid=620457075131776&id=620447568466060&__tn__=-R" target="_blank">仕訳一覧表</a>をご利用ください。
      </p>
    </div>
    <% end %>
    <%= render 'layouts/footer' %>
    <%= debug(params) if Rails.env.development? %>
  </body>
</html>